# Generated by Django 5.0.14 on 2026-07-11 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vehicule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu_depart', models.CharField(max_length=150)),
                ('lieu_arrivee', models.CharField(max_length=150)),
                ('date_depart', models.DateField()),
                ('heure_depart', models.TimeField()),
                ('nombre_places_disponibles', models.PositiveSmallIntegerField()),
                ('prix_par_place', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('publie', 'Publié'), ('complet', 'Complet'), ('annule', 'Annulé'), ('termine', 'Terminé')], default='publie', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trajets', to='api.vehicule')),
            ],
            options={
                'ordering': ['date_depart', 'heure_depart'],
            },
        ),
    ]
