# Generated by Django 5.0.14 on 2026-07-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='etat',
            field=models.CharField(choices=[('en_attente_depart', 'En attente du départ'), ('chauffeur_en_route', 'Chauffeur en route'), ('chauffeur_arrive', 'Chauffeur arrivé'), ('en_cours', 'Trajet en cours'), ('termine', 'Trajet terminé')], default='en_attente_depart', max_length=30),
        ),
    ]
