# Generated by Django 5.0.14 on 2026-07-15 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_trajet_etat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('chauffeur_en_route', 'Chauffeur en route'), ('chauffeur_arrive', 'Chauffeur arrivé'), ('trajet_commence', 'Trajet commencé'), ('trajet_termine', 'Trajet terminé')], max_length=30)),
                ('titre', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('est_lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-date_reservation']},
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('trajet', 'passager'), name='reservation_unique_par_passager_et_trajet'),
        ),
        migrations.AddField(
            model_name='notification',
            name='trajet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.trajet'),
        ),
        migrations.AddField(
            model_name='notification',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
