# Generated by Django 5.0.14 on 2026-07-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_notification_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='titre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('chauffeur_en_route', 'Chauffeur en route'), ('chauffeur_arrive', 'Chauffeur arrivé'), ('trajet_commence', 'Trajet commencé'), ('trajet_termine', 'Trajet terminé'), ('trajet_annule', 'Trajet annulé')], max_length=30),
        ),
    ]
