# Generated by Django 5.0.14 on 2026-07-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_notification_titre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='adresse_rendez_vous',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='latitude_rendez_vous',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='longitude_rendez_vous',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='point_rendez_vous_confirme',
            field=models.BooleanField(default=False),
        ),
    ]
